# # Playbook to call multiple roles to configure systems
# - name: Configure systems
#   hosts: 3.80.159.108
#   become: yes

#   tasks:

# - name: Call Roles
#   hosts: 3.80.159.108
#   roles:
#    #- hostname
#    #- firewalld
#    #- ntp-config
#    - motd

- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
